
# Literature {#literature .unnumbered}

One motivation for supplying you with detailed notes for this
course is the absence of a wholly ideal text book. However, it should be
stressed that while these notes approach (in places) the detail of a
book, the notes are not fully comprehensive and should be regarded as
the 'bare bones' of the course, to be fleshed out via your own reading
and supplementary note taking. To this end perhaps the most appropriate
textbooks are:

A good book at the right level for the phase transitions and critical phenomena part of the course is

+ **[J.M. Yeomans: Statistical Mechanics of Phase Transitions](https://bris.on.worldcat.org/search/detail/24699159?queryString=yeomans%20statistical&clusterResults=true&stickyFacetsChecked=true&groupVariantRecords=false&newsArticles=off&bookReviews=off)**

A good book covering all aspects of this part of the course including non-equilibrium systems is

+ **[D. Chandler:  Introduction to Modern Statistical Mechanics](https://bris.on.worldcat.org/search/detail/941821555?queryString=chandler%20statistical&clusterResults=true&stickyFacetsChecked=true&groupVariantRecords=false&newsArticles=off&bookReviews=off)**

You might also wish to dip into the introductory chapters of the
following more advanced texts


+ **[N Goldenfeld: Lectures on Phase Transitions and the Renormalization Group](https://bris.on.worldcat.org/search/detail/25914535?queryString=Lectures%20on%20Phase%20Transitions%20and%20the%20Renormalization%20Group&clusterResults=true&stickyFacetsChecked=true&groupVariantRecords=false&newsArticles=off&bookReviews=off)** 


+ **[J.J. Binney, N.J. Dowrick, A.J.Fisher and M.E.J. Newman: The Theory of Critical Phenomena](https://bris.on.worldcat.org/search/detail/861559276?queryString=%20The%20Theory%20of%20Critical%20Phenomena&clusterResults=true&stickyFacetsChecked=true&groupVariantRecords=false&newsArticles=off&bookReviews=off)**

 For revision on thermodynamics and statistical mechanics

  + **[F. Mandl: Statistical Physics](https://bris.on.worldcat.org/search/detail/15487191?queryString=F.%20Mandl&clusterResults=true&stickyFacetsChecked=true&groupVariantRecords=false){.external target="_blank"}**. 

  For Stochastic dynamics
  
  + **[N.G. van Kampen: Stochastic processess in Physics and Chemistry](https://bris.on.worldcat.org/search/detail/162131511?queryString=Stochastic%20Processes%20in%20Physics%20and%20Chemistry%20by%20N.G.%20van%20Kampen&clusterResults=true&stickyFacetsChecked=true&groupVariantRecords=false)**