project:
  type: book
  output-dir: ../docs  # Uncomment if you want to specify output directory
  # render:
    # - "Week*/*"

book:
  page-navigation: true
  back-to-top-navigation: true
  #title: "Complex Disordered Matter"
  sidebar:
    smooth-scroll: true
    logo: phase-transitions/Figs/courselogo.png
    style: "docked"
    search: true
    collapse-level: 1
  chapters:
    - href: index.qmd
      text: Overview  
    - part: "Unifying theoretical concepts"
      chapters:
         - href: phase-transitions/literature.qmd
           text: "Recommended texts"
         - text: "Introduction to phase behaviour"
           href:  phase-transitions/introduction.qmd
         - text: "Background concepts"
           href: phase-transitions/background.qmd
         - text: "The approach to criticality"
           href:  phase-transitions/approach-to-criticality.qmd
         - text: "The Ising model"
           href: phase-transitions/Ising-model.qmd            
         - text: "Mean field theory"
           href:  phase-transitions/mean-field-theory.qmd
         - text: "The lattice gas"
           href: phase-transitions/lattice-gas.qmd
         - text: "The static scaling hypothesis"
           href: phase-transitions/scaling.qmd
         - text: "Renormalization group theory"
           href:  phase-transitions/rg.qmd
        #  - text: "RG- the effective coupling viewpoint"
        #    href: phase-transitions/rg-effective-coupling.qmd
         - text: "Nucleation and domain growth"
           href: phase-transitions/nucleation-and-growth.qmd  
         - text: "Introduction to stochastic processes"  
           href: phase-transitions/master-equation-and-diffusion.qmd
         - text: "Brownian and Langevin dynamics"
           href: phase-transitions/Brownian-and-Langevin-dynamics.qmd
         - text: "Dynamics of fluctuations"
           href: phase-transitions/dynamics-of-fluctuations.qmd  
         - href: phase-transitions/problems.qmd
           text: "Problems"   
         - href: phase-transitions/live-test.qmd
           text: "Coding"  

    - part: "Complex disordered matter"
      chapters:
        - href: soft-matter/soft-matter_plan.qmd
          text: "Plan"
        - href: soft-matter/soft-matter_intro.qmd
          text: "Entropy matters"
        - href: soft-matter/soft-matter_colloids.qmd
          text: "Colloids"
        - href: soft-matter/soft-matter_polymers.qmd
          text: "Polymers"
        - href: soft-matter/soft-matter_surfactants.qmd
          text: "Surfactants"
        - href: soft-matter/soft-matter_glasses.qmd
          text: "Glasses"
        - href: soft-matter/soft-matter_readings.qmd
          text: "Readings"
        - href: soft-matter/soft-matter_problems.qmd
          text: "Problems"
    - part: "Experimental techniques"

  appendices:
    - href: revision_guide.qmd
      text: "Revision guide"
    - href: phase-transitions/concepts_map.qmd
      text: "Concept maps"    
format:
  live-html:
    theme: cosmo
    grid:
      sidebar-width: 305px
    toc: true
    pyodide:
        cell-options:
          autorun: true